version: '3.6'

services:

  epokemon.rabbitmq:
    container_name: mdas-api-raul_camison.rabbitmq
    image: rabbitmq:3.9-management
    environment:
        - RABBITMQ_DEFAULT_USER=raulcamison
        - RABBITMQ_DEFAULT_PASS=camisonraul
        - RABBITMQ_DEFAULT_VHOST=raulcamisonhost
    ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
        - "15671:15671"
        - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5        
    networks:
      - epokemonnet  

  epokemon.pokemons:
    image: mdas-api-raul_camison.pokemons
    container_name: pokemon
    build:
      context: .
      dockerfile: deploy/Dockerfile-Reto1
    ports:
      - "3080:80" 
      - "3443:443"
    restart: on-failure  
    depends_on:
      -   epokemon.rabbitmq
    networks:
      - epokemonnet

  epokemon.users:
    image: mdas-api-raul_camison.userfavorites
    container_name: userfavorite
    build:
      context: .
      dockerfile: deploy/Dockerfile-Reto2
    ports:
      - "4080:80" 
      - "4443:443"
    networks:
      - epokemonnet

  epokemon.tests:
    image: mdas-api-raul_camison.tests
    container_name: test
    build:
      context: .
      dockerfile: deploy/Dockerfile-Reto3-Test
    ports:
      - "5080:80" 
      - "5443:443"
    networks:
      - epokemonnet

networks:
    epokemonnet:
        driver: bridge